import {scenes} from './data.js';
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const productUrl=value=>{try{const u=new URL(value);return u.protocol==='https:'&&u.hostname==='www.switchbot.jp'?escape(u.href):'#';}catch{return '#';}};
/** Pure document generation: exporting must never wait for GPU rendering/readback. */
export function renderPlanDocument(plan,{date=new Date().toISOString().slice(0,10)}={}){
 const selected=(plan.scenes||[]).map(id=>scenes.find(s=>s.id===id)).filter(Boolean);
 const roomCards=selected.map(s=>`<article><small>${escape(s.time)} · ${escape(s.room)}</small><h3>${escape(s.label)}</h3><p>${escape(s.body).replace(/\n/g,'<br>')}</p><p class="condition">${escape(s.note)}</p></article>`).join('');
 const rows=(plan.products||[]).map(p=>`<tr data-product="${escape(p.id)}"><td><a href="${productUrl(p.url)}">${escape(p.name)} ↗</a><p>${escape(p.note)}</p></td><td data-required="${escape(p.quantity)}">${escape(p.quantity)}</td><td>${escape(p.owned)}</td><td data-buy="${escape(p.toBuy)}"><strong>${escape(p.toBuy)}</strong></td></tr>`).join('');
 const optional=(plan.optional||[]).map(p=>`<li><a href="${productUrl(p.url)}">${escape(p.name)}</a> — ${escape(p.role)}</li>`).join('');
 return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SwitchBot わが家のプラン</title><style>body{font-family:system-ui,-apple-system,sans-serif;color:#293b34;background:#f6f3ec;max-width:920px;margin:48px auto;padding:24px;line-height:1.8}h1{font-size:clamp(26px,5vw,42px);line-height:1.35}h2{margin-top:42px;font-size:22px}h3{margin:8px 0}small,.condition{font-size:11px;color:#5c6c62}.eyebrow{letter-spacing:.16em;font-size:11px;color:#b04639}.rooms{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}article{background:#fff;padding:20px;border:1px solid #d9ded1;border-radius:12px}p,li{font-size:13px}table{width:100%;border-collapse:collapse}td,th{padding:16px 8px;border-bottom:1px solid #c8d0be;text-align:left;font-size:13px}td:first-child{width:64%}td p{font-size:11px;margin:4px 0}a{color:#a4392b;text-decoration:none}footer{border-top:1px solid #c8d0be;padding-top:24px;margin-top:40px}strong{font-size:20px}.note{padding:16px;background:#e9ece2;border-radius:8px}@media(max-width:560px){body{margin:16px auto;padding:16px}.rooms{grid-template-columns:1fr}td,th{padding:10px 4px;font-size:11px}}@media print{body{background:white;margin:0;max-width:none}article{break-inside:avoid}a{color:inherit}h2{break-after:avoid}tr{break-inside:avoid}}</style></head><body><p class="eyebrow">SWITCHBOT / LIVING WORLD</p><h1>わが家の暮らしプラン</h1><p>${escape(date)} · ${selected.length}つの場面 · カーテン ${escape(plan.windows)}か所 / ${plan.split?'両開き':'片開き'}</p><section class="rooms" aria-label="部屋と場面のプラン">${roomCards}</section><h2>必要な組み合わせ</h2><p>複数の場面で使う製品はまとめて集計。お持ちの台数を差し引いています。</p><table><thead><tr><th>製品・対応条件</th><th>必要</th><th>所有</th><th>追加</th></tr></thead><tbody>${rows}</tbody></table>${optional?`<h2>さらに便利に（必須台数には含みません）</h2><ul>${optional}</ul>`:''}<h2>ご購入前の確認</h2><div class="note">${(plan.warnings||[]).map(w=>`<p>※ ${escape(w)}</p>`).join('')}<p>参考構成です。ドア・レールの適合、家電の対応、通信範囲はご家庭で確認してください。価格・在庫・セット内容は各製品の公式ページをご覧ください。</p></div><footer><small>このファイルはオフラインでも読めます。PDF化はブラウザの「印刷」から行えます。<br>場面の提案であり、実測の設置図ではありません。3D表示の状態によらず同じ計算結果を保存します。</small></footer></body></html>`;
}
/** Native browser download in the original user gesture; no asynchronous GPU work. */
export function downloadPlanDocument(html){
 const blob=new Blob([html],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob);
 const a=document.createElement('a');a.href=url;a.download='SwitchBot-My-Home-Plan.html';a.hidden=true;
 document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);
}
