import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';
const base=process.env.BASE_URL||'http://127.0.0.1:4178',dir=process.env.EVIDENCE_DIR||'spatial-evidence';fs.mkdirSync(dir,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--enable-webgl','--ignore-gpu-blocklist']});
const result={checkedAt:new Date().toISOString(),base,checks:[],errors:[],sourceSha:process.env.SOURCE_SHA||null};const contexts=[];
async function open(viewport,path='?view=3d',reducedMotion='no-preference'){const context=await browser.newContext({viewport,deviceScaleFactor:1,acceptDownloads:true,reducedMotion});contexts.push(context);const page=await context.newPage();page.on('pageerror',e=>result.errors.push(e.message));const r=await page.goto(base+'/'+path,{waitUntil:'domcontentloaded',timeout:60000});assert.equal(r.status(),200);await page.waitForFunction(()=>window.__spatial?.ready&&window.__livingWorld?.canvas.dataset.ready==='true',null,{timeout:90000});return page;}
async function snapshot(page,name){const s=await page.context().newCDPSession(page);const out=await s.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await s.detach();fs.writeFileSync(`${dir}/${name}.png`,Buffer.from(out.data,'base64'));}
const check=name=>{result.checks.push(name);console.log('PASS',name);};
try{
 const page=await open({width:1280,height:800});assert.equal(await page.locator('#fallback').isVisible(),false);
 const a=await page.evaluate(()=>window.__livingWorld.snapshot());await page.waitForTimeout(2400);const b=await page.evaluate(()=>window.__livingWorld.snapshot());assert.ok(b.triangles>5000);assert.ok(Math.hypot(...a.camera.map((v,i)=>v-b.camera[i]))>.45);check('Opening 3D camera orbits actual geometry without user scrolling');
 await page.evaluate(()=>window.__spatial.stopOrbit());await snapshot(page,'01-3d-overview');
 const c=await page.evaluate(()=>window.__livingWorld.snapshot().camera);await page.mouse.move(820,380);await page.mouse.down();await page.mouse.move(1070,410,{steps:8});await page.mouse.up();await page.waitForTimeout(600);const d=await page.evaluate(()=>window.__livingWorld.snapshot().camera);assert.ok(Math.hypot(...c.map((v,i)=>v-d[i]))>.5);check('Pointer drag changes camera in world space');
 await page.locator('[data-room=bedroom]').click();await page.waitForFunction(()=>!window.__livingWorld.roomTransition,null,{timeout:30000});assert.equal(await page.evaluate(()=>window.__livingWorld.house.floor1.visible),false);await snapshot(page,'02-3d-bedroom');check('Bedroom entry isolates the second floor in the same model');
 await page.evaluate(()=>window.__spatial.exit());
 for(const [p,name] of [[0,'03-story-overview'],[.21,'04-story-morning'],[.37,'05-story-leaving'],[.71,'06-story-home'],[.955,'07-story-night']]){await page.evaluate(p=>{window.__app.seek(p,true);window.__livingWorld.renderAt(p);},p);await page.waitForTimeout(120);await snapshot(page,name);}
 const night=await page.evaluate(()=>window.__livingWorld.snapshot());assert.ok(night.state.curtain<.05&&night.state.living<.1);await page.evaluate(()=>{window.__app.seek(.21,true);window.__livingWorld.renderAt(.21);});const morning=await page.evaluate(()=>window.__livingWorld.snapshot());assert.ok(morning.state.curtain>.95);check('Forward and reverse scrub changes curtains lighting and camera');
 await page.locator('#solutionButton').click();assert.equal(await page.locator('#solutionDialog').isVisible(),true);assert.ok(await page.locator('#solutionDialog a[href^="https://www.switchbot.jp/"]').count()>0);await page.locator('#closeDialog').click();check('Scene solutions expose official product links');
 await page.locator('#planNav').click();await page.locator('#windowCount').selectOption('2');await page.locator('[data-owned=curtain]').fill('1');assert.equal(await page.evaluate(()=>window.__currentPlan.products.find(p=>p.id==='curtain').toBuy),3);
 const [download]=await Promise.all([page.waitForEvent('download',{timeout:90000}),page.locator('#exportPlan').click()]);await download.saveAs(`${dir}/example-plan.html`);assert.ok(fs.statSync(`${dir}/example-plan.html`).size>600);check('Consumer plan calculates quantity and downloads a real document');
 const mobile=await open({width:390,height:844});await mobile.evaluate(()=>window.__spatial.stopOrbit());await snapshot(mobile,'08-mobile-3d');assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await mobile.locator('[data-room=living]').click();await mobile.waitForFunction(()=>!window.__livingWorld.roomTransition,null,{timeout:30000});await snapshot(mobile,'09-mobile-living');check('Cold-start mobile 3D with no horizontal overflow');
 const still=await open({width:900,height:700},'?view=3d','reduce');assert.equal(await still.evaluate(()=>window.__spatial.automatic),false);check('Reduced motion disables automatic orbit');assert.deepEqual(result.errors,[]);result.status='PASS';
 if(process.env.CAPTURE_MEDIA==='1'){
  const media=await open({width:960,height:600},'');await media.evaluate(()=>{window.__spatial.stopIntro();window.__spatial.exit();document.querySelector('#stage').classList.add('theatre');window.__livingWorld.renderer.setPixelRatio(1);});
  const frames=`${dir}/frames`;fs.mkdirSync(frames,{recursive:true});
  for(let i=0;i<150;i++){await media.evaluate(({i})=>{const w=window.__livingWorld;if(i<36){window.__app.setMode('explore');w.roomTransition=null;w.spatialComposition=true;w.resize();w.house.roofGroup.visible=false;const theta=.70-i*.012;w.camera.position.set(Math.sin(theta)*19,11,Math.cos(theta)*19);w.controls.target.set(0,2.3,0);w.look.copy(w.controls.target);w.camera.lookAt(w.look);w.renderer.render(w.scene,w.camera);}else{if(i===36){window.__app.setMode('story',false);w.spatialComposition=false;w.resize();document.querySelector('#stage').classList.add('theatre');}const p=(i-36)/113;window.__app.seek(p,true);w.renderAt(p);}},{i});const s=await media.context().newCDPSession(media);const out=await s.send('Page.captureScreenshot',{format:'jpeg',quality:87,captureBeyondViewport:false});await s.detach();fs.writeFileSync(`${frames}/${String(i).padStart(4,'0')}.jpg`,Buffer.from(out.data,'base64'));if(i%30===0)console.log('FRAME',i);}
  result.recording={kind:'deterministic browser-rendered camera preview',frames:150,width:960,height:600,notDeviceFPSMeasurement:true};
  if(fs.existsSync('vendor/three/addons/exporters/GLTFExporter.js')){await media.evaluate(async()=>{const {GLTFExporter}=await import('./vendor/three/addons/exporters/GLTFExporter.js');const w=window.__livingWorld;w.renderAt(.71);w.setFloor('all');w.house.roofGroup.visible=false;w.house.root.updateMatrixWorld(true);const glb=await new GLTFExporter().parseAsync(w.house.root,{binary:true,onlyVisible:true});const bytes=new Uint8Array(glb);let s='';for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,i+32768));window.__modelBase64=btoa(s);});fs.writeFileSync(`${dir}/SwitchBot-Japanese-Home-Cutaway.glb`,Buffer.from(await media.evaluate(()=>window.__modelBase64),'base64'));result.modelExport='GLB cutaway spatial illustration, not product CAD';}
 }
}catch(e){result.status='FAIL';result.failure=e.stack;console.error(e);}
finally{fs.writeFileSync(`${dir}/verification.json`,JSON.stringify(result,null,2));for(const context of contexts)await context.close();await browser.close();}
if(result.status!=='PASS')process.exitCode=1;
