export const productCatalog={
 curtain:{id:'curtain',name:'SwitchBot カーテン3',short:'カーテン3',url:'https://www.switchbot.jp/products/switchbot-curtain3',role:'今あるカーテンを、設定した時間に開閉。',note:'レール形状・寸法を要確認。両開きは通常2台。'},
 lock:{id:'lock',name:'SwitchBot ロックUltra',short:'ロックUltra',url:'https://www.switchbot.jp/products/switchbot-lock-ultra',role:'玄関の施錠・解錠をスマートに。',note:'ドア・サムターンの適合確認が必要です。ドアを開ける動作は人が行います。'},
 keypad:{id:'keypad',name:'SwitchBot 顔認証パッド',short:'顔認証パッド',url:'https://www.switchbot.jp/products/switchbot-keypad-vision',role:'顔認証で、鍵を取り出さず解錠。',note:'対応ロックとの併用・顔の登録と設置位置の調整が必要です。'},
 hub:{id:'hub',name:'SwitchBot ハブ3',short:'ハブ3',url:'https://www.switchbot.jp/products/switchbot-hub3',role:'対応製品・赤外線家電をシーンでまとめる。',note:'2.4GHz Wi-Fi・対応家電・事前設定が必要。設置場所と通信範囲によって必要台数が変わります。'},
 remote:{id:'remote',name:'SwitchBot リモートボタン',short:'リモートボタン',url:'https://www.switchbot.jp/products/switchbot-remote',role:'スマートフォンを開かず、手元から操作。',note:'シーン実行に条件あり。ロックをシーンの実行アクションにできない旨が公式に記載されています。'}
};
export const scenes=[
 {id:'morning',time:'07:00',en:'A softer start',label:'朝',title:'光と、\n目を覚ます。',body:'いつものカーテンが、いつもの時間に。\n朝の小さなひと手間を、家に任せよう。',room:'2F / 寝室',actions:['設定した時間','カーテンが開く','朝の光が入る'],essential:['curtain'],recommended:['hub'],upgrade:['remote'],note:'カーテン3のスケジュールとQuietDriftモードを設定。映像は開閉時間を短縮したイメージです。',trigger:'タイマー',goals:['comfort','ease']},
 {id:'leaving',time:'08:30',en:'Leave the little things',label:'外出',title:'出かける前を、\nもっと軽く。',body:'照明と空調を、シーンでまとめてオフ。\n玄関には、設定したオートロックを。',room:'1F / 玄関 → 家全体',actions:['アプリで外出シーン','対応家電をオフ','ドアを閉めて施錠'],essential:['hub','lock'],recommended:[],upgrade:['remote'],note:'外出シーンはアプリから実行。オートロックは対応条件を確認して別途設定。「最後の一人」を自動判定するデモではありません。',trigger:'アプリ＋設定済みオートロック',goals:['security','energy','ease']},
 {id:'coming-home',time:'18:30',en:'A warmer welcome',label:'帰宅',title:'おかえりで、\n家が整う。',body:'顔で解錠。ドアを開けたら、いつもの家へ。\n対応する照明と家電が、帰宅のシーンをつくる。',room:'1F / 玄関 → リビング',actions:['顔認証で解錠','玄関へ入る','設定した帰宅シーン'],essential:['lock','keypad','hub'],recommended:['curtain'],upgrade:['remote'],note:'対応機器とオートメーションの事前設定が必要です。解錠後、ドアは人が開閉します。照明・空調は対応する既存の赤外線家電を想定。',trigger:'顔認証＋設定済みオートメーション',goals:['security','ease','comfort']},
 {id:'good-night',time:'23:30',en:'One last good night',label:'おやすみ',title:'おやすみを、\n家じゅうに。',body:'カーテン、照明、玄関。\n眠る前の操作を、ひとつのシーンへ。',room:'2F / 寝室 → 家全体',actions:['アプリでおやすみ','カーテンを閉じる','対応照明をオフ'],essential:['hub','curtain'],recommended:['lock'],upgrade:['remote'],note:'アプリに登録したシーンを実行する例です。ドアの閉鎖・施錠状態は別途確認。未対応の家電や遠い部屋には追加機器が必要になる場合があります。',trigger:'アプリのシーン',goals:['security','energy','comfort','ease']}
];
export const rooms=[{id:'all',name:'家全体',floor:'1F + 2F',description:'ひとつの家で、つながる一日。',scenes:scenes.map(s=>s.id)},{id:'entrance',name:'玄関',floor:'1F',description:'鍵を探す時間を、家族との時間に。',scenes:['leaving','coming-home']},{id:'living',name:'リビング',floor:'1F',description:'帰ってきたら、くつろぎの場所。',scenes:['coming-home','good-night']},{id:'bedroom',name:'寝室',floor:'2F',description:'光で始まり、静けさで終わる。',scenes:['morning','good-night']},{id:'outside',name:'アプローチ',floor:'OUTDOOR',description:'門の外から、帰宅は始まる。',scenes:['coming-home','leaving']}];
export const goals=[{id:'comfort',name:'もっと快適に',sub:'朝と夜を心地よく'},{id:'ease',name:'もっとラクに',sub:'毎日の操作を減らす'},{id:'security',name:'もっと安心を',sub:'玄関から備える'},{id:'energy',name:'ムダを減らす',sub:'消し忘れを少なく'}];
