import {chromium} from 'playwright';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve('switchbot-living-world-v5'),out=path.join(root,'evidence/v52');fs.mkdirSync(out,{recursive:true});
const report={version:'5.2.0',checkedAt:new Date().toISOString(),checks:[],errors:[],screenshots:[]};
const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
const page=await browser.newPage({viewport:{width:1280,height:800},deviceScaleFactor:1,acceptDownloads:true});page.setDefaultTimeout(45000);page.on('pageerror',e=>report.errors.push(e.message));
const ok=(name,value)=>{assert.ok(value,name);report.checks.push({name,status:'PASS'});console.log('PASS',name);};
async function shot(name){await page.evaluate(()=>{const w=window.__livingWorld;w.active=false;w.renderer.render(w.scene,w.camera);});const c=await page.context().newCDPSession(page);const image=await c.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(image.data,'base64'));await c.detach();report.screenshots.push(name+'.png');await page.evaluate(()=>{window.__livingWorld.active=true;window.__livingWorld.dirty=true;});}
async function seek(p){return page.evaluate(p=>{window.__spatial.stopIntro();window.__app.stopPlay();window.__app.setMode('story',false);window.__app.seek(p,true);window.__livingWorld.renderAt(p);return window.__livingWorld.snapshot();},p);}
try{
 const r=await page.goto(process.env.BASE_URL||'http://127.0.0.1:4198/',{waitUntil:'domcontentloaded',timeout:60000});assert.equal(r.status(),200);await page.waitForFunction(()=>window.__spatial?.ready&&window.__cinematic?.ready&&window.__livingWorld.frames>0,null,{timeout:60000});
 let a=await seek(0);ok('First frame is the complete facade in real WebGL',a.architecture.finishedExterior&&a.triangles>5000&&!a.contextLost);await shot('01-complete-house');
 a=await seek(.05);ok('Facade continuously reveals the same house',a.architecture.envelopeAlpha>0&&a.architecture.envelopeAlpha<1);await shot('02-reveal');
 const morning=await seek(.22);ok('Camera enters upper room; curtains open; no facade obstruction',morning.camera[1]>4&&morning.camera[1]<6&&morning.state.curtain>.9&&!morning.architecture.lowerVisible);await shot('03-morning');
 a=await seek(.59);ok('Entrance door opens after authentication',a.state.door>.5&&a.state.authenticated);await shot('04-entry');
 const living=await seek(.71);ok('Camera enters ground-floor living with lights on',living.camera[1]<3&&living.state.living>.9&&!living.architecture.lowerVisible);await shot('05-living');
 a=await seek(1);ok('Night returns to the same complete house',a.architecture.finishedExterior&&a.state.curtain===0);await shot('06-complete-night');
 a=await seek(.22);ok('Reverse scroll restores exact camera',JSON.stringify(a.camera)===JSON.stringify(morning.camera));
 await page.evaluate(()=>{window.__app.setMode('explore');window.__app.selectRoom('outside');});await page.waitForFunction(()=>!window.__livingWorld.roomTransition);ok('Explorer uses the same finished exterior',await page.evaluate(()=>window.__livingWorld.snapshot().architecture.finishedExterior));await shot('07-explore-exterior');
 await page.evaluate(()=>window.__app.selectRoom('living'));await page.waitForFunction(()=>!window.__livingWorld.roomTransition);ok('Selecting room reveals the actual first floor',await page.evaluate(()=>!window.__livingWorld.snapshot().architecture.lowerVisible&&!window.__livingWorld.house.floor2.visible));
 await page.locator('#tryCurtain').click();ok('Try action changes actual curtain state',await page.evaluate(()=>typeof window.__livingWorld.preview.curtain==='number'));
 await page.locator('#planNav').click();await page.locator('#windowCount').selectOption('2');await page.locator('[data-owned="curtain"]').fill('1');ok('Plan deducts owned motors once',await page.evaluate(()=>window.__currentPlan.products.find(x=>x.id==='curtain').toBuy===3));
 const dp=page.waitForEvent('download',{timeout:45000});await page.locator('#exportPlan').click();const d=await dp;await d.saveAs(path.join(out,'example-plan.html'));ok('Save creates an actual self-contained plan file',fs.readFileSync(path.join(out,'example-plan.html'),'utf8').includes('SwitchBot'));
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{window.__app.setMode('explore');window.__app.selectRoom('outside');});await page.waitForFunction(()=>!window.__livingWorld.roomTransition);const distance=await page.evaluate(()=>{const w=window.__livingWorld;return w.camera.position.distanceTo(w.controls.target);});ok('Portrait retains intended exterior distance; no 37m clamp',distance>55);await shot('08-mobile-exterior');ok('Portrait has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await seek(.22);await shot('09-mobile-morning');await seek(.71);await shot('10-mobile-living');
 await page.evaluate(()=>window.__spatial.enter(false));await page.waitForFunction(()=>!window.__livingWorld.roomTransition);await page.evaluate(()=>window.__spatial.startOrbit());await page.waitForTimeout(400);ok('Automatic orbit preserves the exterior selection',await page.evaluate(()=>window.__livingWorld.roomId==='outside'&&window.__livingWorld.snapshot().architecture.finishedExterior));await page.evaluate(()=>window.__spatial.stopOrbit());
 const offline=await browser.newContext({offline:true,viewport:{width:1280,height:800},acceptDownloads:true});const pp=await offline.newPage();const requests=[];pp.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await pp.goto('file://'+path.join(root,'portable/SwitchBot-Living-World-V5.html'),{waitUntil:'domcontentloaded',timeout:60000});await pp.waitForFunction(()=>window.__spatial?.ready&&window.__livingWorld.frames>0,null,{timeout:60000});await pp.evaluate(()=>{window.__spatial.stopIntro();window.__app.stopPlay();});await pp.locator('#planNav').click();const op=pp.waitForEvent('download',{timeout:45000});await pp.locator('#sharePlan').click();const od=await op;await od.saveAs(path.join(out,'offline-shared-plan.html'));ok('Offline sharing saves a file, not a null-origin URL',fs.statSync(path.join(out,'offline-shared-plan.html')).size>1000);ok('Portable 3D makes zero external requests',requests.length===0);await offline.close();
 const rc=await browser.newContext({reducedMotion:'reduce',viewport:{width:390,height:844}}),rp=await rc.newPage();await rp.goto(process.env.BASE_URL||'http://127.0.0.1:4198/');await rp.waitForFunction(()=>window.__spatial?.ready);await rp.locator('#startExperience').click();ok('Reduced-motion uses a chapter step without autoplay',await rp.locator('#playToggle').getAttribute('aria-pressed')==='false');await rc.close();ok('No page JavaScript errors',report.errors.length===0);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);try{await shot('failure');}catch{}process.exitCode=1;}finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser.close();}
